#!/usr/bin/env node
var exec = require('child_process').exec;

var gear = require('gear'),
    queue = new gear.Queue({
        registry: new gear.Registry({
            module: 'gear-lib'
        })
    });

queue.read(['yui-min.js', 'ts.js']).jslint().jsminify().write('ts.min.js').run(function () {
    exec('mv ts.min.js ./yhack_be/htdocs/lib/', function (err, stdout, stderr) {
        if (err) {
            console.log(err, 'error');
        }
    });
});
